add_executable(linear_huffman_c_cpp_test quantizer_huffman_c_cpp_test.cpp)
target_link_libraries(linear_huffman_c_cpp_test PRIVATE SZ3)
add_test(NAME linear_huffman_c_cpp_test COMMAND linear_huffman_c_cpp_test)

add_executable(interpolation_decomposition_c_cpp_test interpolation_decomposition_c_cpp_test.cpp)
target_link_libraries(interpolation_decomposition_c_cpp_test PRIVATE SZ3)
add_test(NAME interpolation_decomposition_c_cpp_test COMMAND interpolation_decomposition_c_cpp_test)

add_executable(quantizer_huffman_i32_c_cpp_test quantizer_huffman_i32_c_cpp_test.cpp)
target_link_libraries(quantizer_huffman_i32_c_cpp_test PRIVATE SZ3)
add_test(NAME quantizer_huffman_i32_c_cpp_test COMMAND quantizer_huffman_i32_c_cpp_test)
